services:
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-c", "/etc/nats/nats-server.conf"]
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoring
      - "7422:7422"   # leafnodes (unused, but handy)
    volumes:
      - ./nats/config:/etc/nats
      - ./nats/data:/var/lib/nats
    restart: unless-stopped

  nats-box:
    image: synadia/nats-box:latest
    depends_on: [nats]
    environment:
      - NATS_URL=nats://nats:4222
    entrypoint: ["/bin/sh","-lc","sleep infinity"]